### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by ashafizullah** [wangli66/vue-leaflet-more#1]
After import vueLeaflet in app.js and use that, and add basic of LMap i my view, then the map is not showing, only show blank. In console log, there is an error Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trim')

My project based on Laravel Vue.Js 3

**Comment by wangli66** [comment]
@ashafizullah Thank you for your feedback. This component is developed based on vue2.0. If you need to use the functions of this component in vue3, please download vue3-leaflet on npm to use。
